'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Crm_Trm_Inbox_EmailSystemMgr

    '''<summary>
    '''TrxID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TrxID As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''TrxUserName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TrxUserName As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''TrxEmailID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TrxEmailID As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''TrxGenerateEmailID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TrxGenerateEmailID As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''Hd_StartDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Hd_StartDate As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''Hd_FinishDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Hd_FinishDate As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''DraftID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DraftID As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''HDSignature control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HDSignature As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''CustomerID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CustomerID As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''TrxCustomerID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TrxCustomerID As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''TrxEmailAccount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TrxEmailAccount As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''TrxTicketNumber control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TrxTicketNumber As Global.System.Web.UI.WebControls.HiddenField
End Class
