'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Crm_MySql_Connection

    '''<summary>
    '''LoginValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LoginValue As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''LogoutValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LogoutValue As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''Button_MySqlConnection control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Button_MySqlConnection As Global.System.Web.UI.HtmlControls.HtmlButton

    '''<summary>
    '''TestingLogin control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TestingLogin As Global.System.Web.UI.HtmlControls.HtmlButton

    '''<summary>
    '''TestingLogout control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TestingLogout As Global.System.Web.UI.HtmlControls.HtmlButton
End Class
