'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class QA_Form

    '''<summary>
    '''TrxID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TrxID As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''QM_AgentID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents QM_AgentID As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''QM_HeaderID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents QM_HeaderID As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''QM_AcraID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents QM_AcraID As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''QM_ResultPenilaianID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents QM_ResultPenilaianID As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''QM_AudioName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents QM_AudioName As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''QM_Persen control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents QM_Persen As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''QM_CustomerID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents QM_CustomerID As Global.System.Web.UI.WebControls.HiddenField
End Class
