'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class SCH_Callendar_Schedule

    '''<summary>
    '''hd_DateRequest control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hd_DateRequest As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hd_AgentTarget control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hd_AgentTarget As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hd_DateChangeTarget control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hd_DateChangeTarget As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hd_JamRequest control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hd_JamRequest As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hd_JamTarget control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hd_JamTarget As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hd_ChannelTarget control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hd_ChannelTarget As Global.System.Web.UI.WebControls.HiddenField
End Class
