'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Uidesk

    '''<summary>
    '''aspxLiteral control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents aspxLiteral As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''ContentPlaceHolder1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ContentPlaceHolder1 As Global.System.Web.UI.WebControls.ContentPlaceHolder

    '''<summary>
    '''hd_TicketNumber control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hd_TicketNumber As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hd_EscalationIdentity control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hd_EscalationIdentity As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hd_EscalationTo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hd_EscalationTo As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hd_sessionLogin control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hd_sessionLogin As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''TrxLoginTypeAngka control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TrxLoginTypeAngka As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''TrxLayerUser control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TrxLayerUser As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''TrxDivisi control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TrxDivisi As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hd_customerID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hd_customerID As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hd_OtherSystem control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hd_OtherSystem As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hd_ThreadSystem control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hd_ThreadSystem As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hd_AccountChannelUser control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hd_AccountChannelUser As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hd_AccountContactUser control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hd_AccountContactUser As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hd_SLA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hd_SLA As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hd_Journey_EscalationType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hd_Journey_EscalationType As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hd_Journey_EscalationValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hd_Journey_EscalationValue As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''HiddenField3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HiddenField3 As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''HiddenField4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HiddenField4 As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hd_NameKaryawan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hd_NameKaryawan As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hd_LevelUser control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hd_LevelUser As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hd_EmailUserLogin control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hd_EmailUserLogin As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''HD_SiteID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HD_SiteID As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''SM_AccountToken control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SM_AccountToken As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''SM_AccountID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SM_AccountID As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''SM_AccountName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SM_AccountName As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''SM_AccountURL control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SM_AccountURL As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''SM_Webhook control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SM_Webhook As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''SM_MultiChatToken control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SM_MultiChatToken As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''SM_UrlDatakelola control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SM_UrlDatakelola As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''SM_CompanyToken control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SM_CompanyToken As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''HD_CookiesVariabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HD_CookiesVariabel As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hd_SIP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hd_SIP As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''HD_UserType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HD_UserType As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''QM_LevelUser control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents QM_LevelUser As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''QM_GroupQA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents QM_GroupQA As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''QM_GroupAgent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents QM_GroupAgent As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''QM_TypeCall control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents QM_TypeCall As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''QM_GroupLayanan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents QM_GroupLayanan As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''QM_TeamLayanan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents QM_TeamLayanan As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hd_AgentScheduleID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hd_AgentScheduleID As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''ChannelAssigned control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ChannelAssigned As Global.System.Web.UI.WebControls.HiddenField
End Class
